name: Use Secrets
on:
  push:
    paths:
      - ".github/workflows/use-secrets.yml"

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grade use-secrets activity
        id: check-secrets
        uses: ./.github/actions/check-secrets-action
        with:
          your-secret: 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
          secrets-context: ${{ toJSON(secrets) }}
